project:
  name: human_mouse_pancreas_ocr
  output_dir: results
  temp_dir: tmp

comparison:
  species_1_name: human
  species_2_name: mouse
  species_1_hal_name: Human
  species_2_hal_name: Mouse
  organ: pancreas

peaks:
  species_1_peak_file: ./data/HumanAtac/Pancreas/peak/idr_reproducibility/idr.optimal_peak.narrowPeak.gz
  species_2_peak_file: ./data/MouseAtac/Pancreas/peak/idr_reproducibility/idr.optimal_peak.narrowPeak.gz

alignments:
  hal_file: ./data/Alignments/10plusway-master.hal

tools:
  orthologfind_py: ./external/halLiftover-postprocessing/orthologFind.py

parameters:
  run_bidirectional_liftover: true
  min_peak_length: 50
  max_peak_length: 1000
  protect_dist: 5