project:
  name: human_mouse_pancreas_ocr
  output_dir: results
  temp_dir: tmp

comparison:
  species_1_name: human
  species_2_name: mouse
  species_1_hal_name: Human
  species_2_hal_name: Mouse
  organ: pancreas

peaks:
  species_1_peak_file: ./data/HumanAtac/Pancreas/peak/idr_reproducibility/idr.optimal_peak.narrowPeak.gz
  species_2_peak_file: ./data/MouseAtac/Pancreas/peak/idr_reproducibility/idr.optimal_peak.narrowPeak.gz

alignments:
  hal_file: ./data/Alignments/10plusway-master.hal

tools:
  orthologfind_py: ./external/halLiftover-postprocessing/orthologFind.py

parameters:
  run_bidirectional_liftover: true
  min_peak_length: 50
  max_peak_length: 1000
  protect_dist: 5

cluster:
  use_sbatch: true
  partition: RM-shared      # partition requested
  nodes: 1                  # number of nodes
  ntasks: 32                # number of cores to allocate per node
  mem: 64000MB              # passed to sbatch as --mem
  allocation_id: bio230007p
  time: "72:00:00"          # walltime limit

halper_outputs:
  species_1_to_species_2: ./results/halper/human_to_mouse/Human_to_Mouse.orthologs.bed
  species_2_to_species_1: ./results/halper/mouse_to_human/Mouse_to_Human.orthologs.bed
